approvals:
  # PR needs at least 2 approvals
  minimum: 1
  # approval = comment that matches this regex
  pattern: "^(:\\+1:|??)$"
  veto:
    # veto/blocking a PR = comment that matches this regex
    pattern: "^(:\\-1:|??)$"
  # note that `from` is by default empty,
  # accepting any matching comment as approval
  from:
    # commenter must be either one of:
    orgs:
      # a public zalando org member
      # (any org in here counts)
      #- zalando
    # OR a collaborator of the repo
    collaborators: true
    # OR one of these guys
    users:
      - user-test
      - user-test2
  # you can define groups from which you
  # require approvals

commit:
  message:
    # note that there are no default patterns for commit messages
    patterns:
      - "^#[0-9]+" # has to begin with hash # and at least one number
autobranch:
  # things in curly brackets are variables that
  # will be replaced. possible variables:
  # - number: the issue number
  # - title: the issue title
  # - labels: the labels of the issue at opening time
  pattern: "{number}-{title}"
  # restrict branch name to maximum this many characters
  length: 60
